apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-aleo-program-job
  labels:
    app: {{ include "aleo-zk-compliance.name" . }}
spec:
  template:
    spec:
      containers:
        - name: leo-container
          image: ubuntu:20.04  # Use a base image, like Ubuntu
          command:
            - /bin/bash
            - -c
            - |
                # Install dependencies
                apt-get update && apt-get install -y curl build-essential git libssl-dev pkg-config
                # Install Leo (Aleo)
                curl -fsSL https://raw.githubusercontent.com/aleo-hq/leo/main/install.sh | bash
                # Add Aleo tools to PATH
                export PATH="$PATH:/root/.cargo/bin"
                # Run Aleo command to initialize the program
                leo run initialize_program  # Replace with your specific Aleo task/command
          env:
            - name: "LEO_PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ include "aleo-zk-compliance.fullname" . }}
                  key: aleo-private-key
            - name: "GCP_SA_JSON"
              valueFrom:
                secretKeyRef:
                  name: {{ include "aleo-zk-compliance.fullname" . }}
                  key: gcp-sa-json
      restartPolicy: Never
  backoffLimit: 4
