apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aleo-zk-compliance.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 5Gi 
  storageClassName: standard  