---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "aleo-zk-compliance.fullname" . }}
    labels:
        {{- include "aleo-zk-compliance.labels" . | nindent 4 }}
data:
    gcp-sa-json: {{ .Values.gcpServiceAccount | toString | b64enc }}